[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 100, lines = 40 }
padding = { x = 5, y = 5 }
decorations = "Buttonless"

opacity = 0.5
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 15
offset = { x = 3, y = 3 }

[general]
import = ["~/.config/alacritty/themes/coolnight.toml"]
